services:
  App\Series\Application\:
    resource: '../../Application/*'
    exclude:
      - '../../Application/*/*Query.php'
      - '../../Application/*/*Request.php'
      - '../../Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\Series\UI\Backoffice\Controller\:
    resource: '../../UI/Backoffice/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\Series\UI\Backoffice\Presenter\:
    resource: '../../UI/Backoffice/Presenter'
    autowire: true
    autoconfigure: true

  App\Series\UI\Backoffice\FormHandler\:
    resource: '../../UI/Backoffice/FormHandler'
    autowire: true
    autoconfigure: true

  App\Series\Domain\Repository\SeriesRepositoryInterface: '@App\Series\Infrastructure\Persistence\DoctrineSeriesRepository'
  App\Series\Domain\Repository\SeriesTypeRepositoryInterface: '@App\Series\Infrastructure\Persistence\DoctrineSeriesTypeRepository'
  App\Series\Domain\Repository\SeriesStyleRepositoryInterface: '@App\Series\Infrastructure\Persistence\DoctrineSeriesStyleRepository'

  App\Series\Infrastructure\Persistence\DoctrineSeriesTypeRepository:
    autowire: true
    autoconfigure: true

  App\Series\Infrastructure\Persistence\DoctrineSeriesStyleRepository:
    autowire: true
    autoconfigure: true

  App\Series\Application\List\ListSeriesService:
    arguments:
      $repository: '@App\Series\Domain\Repository\SeriesRepositoryInterface'

  App\Series\Infrastructure\Persistence\DoctrineSeriesRepository:
    autowire: true
    autoconfigure: true
    public: false
    tags: [ 'doctrine.repository' ]

  App\Series\UI\Backoffice\Twig\SeriesExtension:
    arguments:
      $picService: '@Pumukit\SchemaBundle\Services\PicService'
      $getSeriesOwnersService: '@App\Series\Application\ViewSeriesOwners\GetSeriesOwnersService'
    tags:
      - { name: twig.extension }

  App\Series\Domain\Factory\SeriesFactoryInterface:
    alias: App\Series\Infrastructure\Factory\SeriesFactoryAdapter

  App\Series\Infrastructure\Factory\SeriesFactoryAdapter:
    arguments:
      $factoryService: '@Pumukit\SchemaBundle\Services\FactoryService'
      $userRepository: '@App\User\Domain\Repository\UserRepositoryInterface'

  App\Series\UI\Backoffice\EventSubscriber\:
    resource: '../../UI/Backoffice/EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true
