group_create:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\CreateGroupController
  path: /admin/backend/group/new
  methods: [POST]

group_view:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ViewGroupController
  path: /admin/backend/group/{id}/{tab}
  defaults:
    tab: 'general'
  requirements:
    tab: '[a-z_-]+'

group_delete:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupController
  path: /admin/backend/group/{id}/delete

group_update:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupController
  path: /admin/backend/group/{id}/update

groups_list_data:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupDataController
  path: /admin/backend/groups/data

group_list:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupController
  path: /admin/backend/groups

group_add_user:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\AddUserToGroupController
  path: /admin/backend/group/{id}/add-user
  methods: [POST]

group_remove_user:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\RemoveUserFromGroupController
  path: /admin/backend/group/{id}/remove-user
  methods: [POST]

group_users_data:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\GroupUsersDataController
  path: /admin/backend/group/{id}/users/data

group_multimedia_objects_data:
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\GroupMultimediaObjectsDataController
  path: /admin/backend/group/{id}/multimedia-objects/data

