groups_list_data:
  path: /admin/backend/groups/data
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupDataController

group_list:
  path: /admin/backend/groups
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ListGroupController

group_bulk_delete:
  path: /admin/backend/groups/bulk-delete
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\BulkDeleteGroupController
  methods: [POST]

group_create:
  path: /admin/backend/group/new
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\CreateGroupController
  methods: [POST]

group_delete:
  path: /admin/backend/group/{id}/delete
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\DeleteGroupController
  methods: [POST, DELETE]

group_update:
  path: /admin/backend/group/{id}/update
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\UpdateGroupController

group_view:
  path: /admin/backend/group/{id}/{tab}
  controller: App\IdentityAndAccess\Group\Infrastructure\Ui\Backoffice\Http\Controller\ViewGroupController
  defaults:
    tab: 'general'
