api_platform:
    mapping:
        paths: [
          '%kernel.project_dir%/src/Pumukit/EncoderBundle/Document',
          '%kernel.project_dir%/src/Pumukit/SchemaBundle/Document',
          '%kernel.project_dir%/src/Pumukit/StatsBundle/Document',
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
