api_platform:
    title: 'PuMuKIT API'
    description: 'PuMuKIT API documentation'
    version: '0.1'
    show_webby: false
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    enable_entrypoint: true
    enable_docs: true
    doctrine:
      enabled: false
    doctrine_mongodb_odm:
      enabled: true
    mapping:
        paths: [
          '%kernel.project_dir%/config/api_platform'
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
