doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: '%env(resolve:MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: true
      filters:
        frontend:
          class:     Pumukit\CoreBundle\Filter\WebTVFilter
          enabled:   false
        backoffice:
          class:     Pumukit\CoreBundle\Filter\AdminFilter
          enabled:   false
        personal:
          class:     Pumukit\CoreBundle\Filter\PersonalFilter
          enabled:   false
        microsite:
          class:     Pumukit\CoreBundle\Filter\MicrositeFilter
          enabled:   false
      mappings:
        App:
          is_bundle: false
          type: annotation
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          alias: App
