pumukit_encoder:
  thumbnail:
    width: 768
    height: 432
  cpus:
    local:
      host: 127.0.0.1
  profiles:
    master_copy:
      display: false
      wizard: true
      master: true
      tags: copy
      resolution_hor: 0
      resolution_ver: 0
      audio: false
      bat: cp "{{input}}" "{{output}}"
      streamserver:
        dir_out: "%pumukit.masters_dir%"
    video_master_encoded:
      display: false
      wizard: true
      master: true
      extension: mp4
      resolution_hor: 0
      resolution_ver: 0
      audio: false
      bat: ffmpeg -y -i "{{input}}" -acodec libfdk_aac -b:a 128k -ac 2 -ar 44100 -vcodec libx264 -preset slow -crf 15 -threads 0 "{{output}}"
      streamserver:
        dir_out: "%pumukit.masters_dir%"
        url_out: "%pumukit.downloads_url%"
    video_master_broadcastable:
      display: true
      wizard: true
      master: true
      target: PUCHWEBTV
      extension: mp4
      resolution_hor: 0
      resolution_ver: 0
      audio: false
      bat: ffmpeg -y -i "{{input}}" -acodec libfdk_aac -b:a 128k -ac 2 -ar 44100 -vcodec libx264 -preset slow -crf 22 -movflags faststart -threads 0 "{{output}}"
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    video_broadcastable_dynamic_quality:
      generate_pic: false
      display: true
      wizard: true
      master: false
      nocheckduration: false
      tags: html5 podcast dynamic
      target: PUCHWEBTV PUCHPODCAST PUCHPODDIUM
      extension: m3u8
      resolution_hor: 0
      resolution_ver: 0
      audio: false
      bat: ffmpeg -y -i "{{input}}" -c:v libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v 4M -maxrate:v 4M -bufsize:v 4M -pix_fmt yuv420p -tune film -preset slow -g 50 -sc_threshold 0 -crf 20 -keyint_min 50 -c:a libfdk_aac -b:a 128k -ac 2 -f hls -hls_time 10 -hls_init_time 1 -hls_playlist_type vod -hls_flags independent_segments -hls_segment_type mpegts -hls_segment_filename "{{output_dirname}}/data_%%03d.ts" -master_pl_name "{{output_filename}}.m3u8" "{{output_dirname}}/index.m3u8" -threads 0 -shortest
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    video_broadcastable:
      generate_pic: false
      display: true
      wizard: true
      master: false
      tags: html5 podcast
      target: PUCHWEBTV PUCHPODCAST
      extension: mp4
      resolution_hor: 0
      resolution_ver: 0
      audio: false
      bat: ffmpeg -y -i "{{input}}" -acodec libfdk_aac -b:a 128k -ac 2 -ar 44100 -vcodec libx264 -preset slow -crf 22 -movflags faststart -threads 0 "{{output}}"
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    audio_broadcastable:
      display: true
      wizard: true
      master: false
      tags: html5 audio podcast
      target: PUCHWEBTV PUCHPODCAST*
      extension: m4a
      resolution_hor: 0
      resolution_ver: 0
      audio: true
      bat: ffmpeg -y -i "{{input}}" -acodec libfdk_aac -b:a 128k -ac 2 -ar 44100 -vn -threads 0 "{{output}}"
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    image_broadcastable:
      image: true
      display: true
      wizard: true
      master: false
      tags: html5 image
      target: PUCHWEBTV
      audio: false
      bat: convert "{{input}}" -compress JPEG -quality 90 "{{output}}"
      extension: jpg
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    image_raw_broadcastable:
      image: true
      display: true
      wizard: true
      master: false
      tags: html5 image raw
      target: PUCHWEBTV
      audio: false
      bat: darktable-cli "{{input}}" "{{output}}" --core --conf plugins/imageio/format/jpeg/quality=90
      extension: jpg
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"
    document_broadcastable:
      document: true
      display: true
      wizard: true
      master: false
      tags: html5 document
      target: PUCHWEBTV
      audio: false
      bat: cp "{{input}}" "{{output}}"
      streamserver:
        dir_out: "%pumukit.downloads_dir%"
        url_out: "%pumukit.downloads_url%"

  target_default_profiles:
    PUCHWEBTV:
      audio: "audio_broadcastable"
      video: "video_broadcastable"
      image: "image_broadcastable"
      image_raw: "image_raw_broadcastable"
      document: "document_broadcastable"
    PUCHPODCAST:
      audio: "audio_broadcastable"
      video: "video_broadcastable audio_broadcastable"