framework:
  messenger:
    transports:
      pumukit.youtube.quota.waiting:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: pumukit.exchange
            type: direct
          queues:
            pumukit.youtube.quota.waiting:
              binding_keys: ['#']

      pumukit.youtube.events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: pumukit.exchange
            type: direct
          queues:
            pumukit.youtube.events:
              binding_keys: ['#']

      pumukit.youtube.notifications:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: pumukit.exchange
            type: direct
          queues:
            pumukit.youtube.notifications:
              binding_keys: ['#']

    routing:
      App\Message\WaitingMessage: pumukit.youtube.quota.waiting
      App\Message\EventMessage: pumukit.youtube.events
      App\Message\NotificationMessage: pumukit.youtube.notifications

