services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  Pumukit\StatsBundle\Controller\:
    resource: '../../src/Pumukit/StatsBundle/Controller/'
    tags: ['controller.service_arguments']

  Pumukit\StatsBundle\Command\:
    resource: '../../src/Pumukit/StatsBundle/Command/'
    tags: ['console.command']

  Pumukit\StatsBundle\EventListener\Log:
    class: Pumukit\StatsBundle\EventListener\Log
    tags:
      - { name: "kernel.event_listener", event: "multimediaobject.view", method: "onMultimediaObjectViewed" }

  Pumukit\StatsBundle\Services\StatsService:
    class: Pumukit\StatsBundle\Services\StatsService
    arguments:
      $useAggregation: '%pumukit_stats.use_aggregation%'
