services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  Pumukit\UserBundle\Controller\:
    resource: '../../src/Pumukit/UserBundle/Controller'
    tags: ['controller.service_arguments']

  Pumukit\UserBundle\Command\:
    resource: '../../src/Pumukit/UserBundle/Command'
    tags: ['console.command']

  Pumukit\UserBundle\Security\LoginFormAuthenticator:
    class: Pumukit\UserBundle\Security\LoginFormAuthenticator

  Pumukit\UserBundle\Services\CreateUserService:
    class: Pumukit\UserBundle\Services\CreateUserService
