services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  Pumukit\BaseLivePlayerBundle\Controller\:
    resource: '../../src/Pumukit/BaseLivePlayerBundle/Controller/'
    tags: ['controller.service_arguments']

  Pumukit\BaseLivePlayerBundle\Twig\LiveTwigExtension:
    arguments:
      $eventDefaultPic: "%pumukit_new_admin.advance_live_event_create_default_pic%"
    tags:
      - { name: "twig.extension" }

  Pumukit\BaseLivePlayerBundle\Services\LiveService:
    class: Pumukit\BaseLivePlayerBundle\Services\LiveService

  Pumukit\BaseLivePlayerBundle\Services\APIService:
    class: Pumukit\BaseLivePlayerBundle\Services\APIService
