twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  paths:
    '%kernel.project_dir%/src/Dashboard': Dashboard
    '%kernel.project_dir%/src/MultimediaObject': MultimediaObject
    '%kernel.project_dir%/src/Series': Series
    '%kernel.project_dir%/src/Shared': Shared
    '%kernel.project_dir%/src/Taxonomy': Taxonomy
    '%kernel.project_dir%/src/User': User
  globals:
    pumukit_info:  "%pumukit.info%"
    locales:       "%pumukit.locales%"
    enable_cookie_banner: '%env(bool:ENABLE_COOKIE_BANNER)%'
    cookie_banner_privacy_link: "%env(COOKIE_BANNER_PRIVACY_LINK)%"
