twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  paths:
    '%kernel.project_dir%/src/UI/Backoffice/Analytics': Analytics
    '%kernel.project_dir%/src/UI/Backoffice/Dashboard': Dashboard
    '%kernel.project_dir%/src/UI/Backoffice/ContentManagement/MultimediaObject': MultimediaObject
    '%kernel.project_dir%/src/UI/Backoffice/ContentManagement/Playlist': Playlist
    '%kernel.project_dir%/src/UI/Backoffice/ContentManagement/Series': Series
    '%kernel.project_dir%/src/UI/Backoffice/Shared': Shared
    '%kernel.project_dir%/src/UI/Backoffice/Streaming': Streaming
    '%kernel.project_dir%/src/UI/Backoffice/ContentManagement/Taxonomy': Taxonomy
    '%kernel.project_dir%/src/UI/Backoffice/MediaProcessing/Job': Job
    '%kernel.project_dir%/src/UI/Backoffice/MediaProcessing/Cpu': Cpu
    '%kernel.project_dir%/src/UI/Backoffice/IdentityAndAccess': User
  globals:
    pumukit_info:  "%pumukit.info%"
    locales:       "%pumukit.locales%"
    enable_cookie_banner: '%env(bool:ENABLE_COOKIE_BANNER)%'
    cookie_banner_privacy_link: "%env(COOKIE_BANNER_PRIVACY_LINK)%"
