twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  paths:
    '%kernel.project_dir%/src/Analytics/Infrastructure/Ui/Backoffice/Http': Analytics
    '%kernel.project_dir%/src/Streaming/Channel/Infrastructure/Ui/Backoffice/Http': Channel
    '%kernel.project_dir%/src/Shared/Infrastructure/Ui/Backoffice/Http': Shared
    '%kernel.project_dir%/src/IdentityAndAccess/User/Infrastructure/Ui/Backoffice/Http': User
    '%kernel.project_dir%/src/MediaProcessing/Job/Infrastructure/Ui/Backoffice/Http': Job
    '%kernel.project_dir%/src/MediaProcessing/Cpu/Infrastructure/Ui/Backoffice/Http': Cpu
    '%kernel.project_dir%/src/Taxonomy/Tag/Infrastructure/Ui/Backoffice/Http': Tag
    '%kernel.project_dir%/src/Playlist/Infrastructure/Ui/Backoffice/Http': Playlist
    '%kernel.project_dir%/src/ContentManagement/MultimediaObject/Infrastructure/Ui/Backoffice/Http': MultimediaObject
    '%kernel.project_dir%/src/ContentManagement/Person/Infrastructure/Ui/Backoffice/Http': Person
    '%kernel.project_dir%/src/ContentManagement/Series/Infrastructure/Ui/Backoffice/Http': Series
    '%kernel.project_dir%/src/ContentManagement/Role/Infrastructure/Ui/Backoffice/Http': Role
  globals:
    pumukit_info:  "%pumukit.info%"
    locales:       "%pumukit.locales%"
    enable_cookie_banner: '%env(bool:ENABLE_COOKIE_BANNER)%'
    cookie_banner_privacy_link: "%env(COOKIE_BANNER_PRIVACY_LINK)%"
