services:
  php:
    env_file:
      - .env.test
    build:
      context: ./
      target: production
      cache_from:
        - teltek/pumukit
        - teltek/nginx
    depends_on:
      - db
      - redis
    volumes:
      - ./:/srv/pumukit

  db:
    image: mongo:8.0

  redis:
    image: redis
    env_file:
      - .env.test
