services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\ContentManagement\Person\Domain\Repository\PersonRepositoryInterface:
        class: App\ContentManagement\Person\Infrastructure\Persistence\DoctrinePersonRepository
    App\ContentManagement\Person\Application\CreatePerson\CreatePersonService: ~
    App\ContentManagement\Person\Application\UpdatePerson\UpdatePersonService: ~
    App\ContentManagement\Person\Application\ViewPerson\ViewPersonService: ~
    App\ContentManagement\Person\Application\ListPersons\ListPersonsService: ~
    App\ContentManagement\Person\Application\DeletePerson\DeletePersonService: ~
    App\ContentManagement\Person\Infrastructure\Persistence\DoctrinePersonRepository: ~
    App\UI\Backoffice\ContentManagement\Person\Controller\:
        resource: '../../../UI/Backoffice/ContentManagement/Person/Controller'
        tags: ['controller.service_arguments']
    App\UI\Backoffice\ContentManagement\Person\Presenter\PersonDataTablePresenter: ~
    App\UI\Backoffice\ContentManagement\Person\EventSubscriber\:
        resource: '../../../UI/Backoffice/ContentManagement/Person/EventSubscriber'
        tags: [ 'kernel.event_subscriber' ]
        autowire: true
        autoconfigure: true
    App\ContentManagement\Person\Infrastructure\EventSubscriber\PersonEventSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        autowire: true
        autoconfigure: true
