<?php

namespace Pumukit\TemplateBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TemplateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends DocumentRepository
{
}
