<?php

namespace Pumukit\LiveBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LiveRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveRepository extends DocumentRepository
{
    /**
     * Create a query builder sorted by name.
     *
     * @param string $locale
     *
     * @return \Doctrine\MongoDB\Query\Builder
     */
    public function createAbcSortQueryBuilder($locale = 'en')
    {
        return $this->createQueryBuilder()
            ->sort('name.'.$locale, 1)
        ;
    }
}
