<?php

namespace Pumukit\LiveBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveRepository extends DocumentRepository
{
}
