# Bulk operations first
user_create:
  path: /admin/backend/users
  controller: App\User\UI\Backoffice\Controller\ListUserController

user_list:
  path: /admin/backend/users
  controller: App\User\UI\Backoffice\Controller\ListUserController

users_list_data:
  path: /admin/backend/users/data
  controller: App\User\UI\Backoffice\Controller\ListUserDataController
