services:
  App\User\Application\:
    resource: '../../../../Application/*'
    exclude:
      - '../../../../Application/*/*Query.php'
      - '../../../../Application/*/*Request.php'
      - '../../../../Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\User\UI\Backoffice\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\User\Domain\Repository\UserRepositoryInterface: '@App\User\Infrastructure\Persistence\DoctrineUserRepository'

  App\Series\Application\List\ListSeriesService:
    arguments:
      $repository: '@App\Series\Domain\Repository\SeriesRepositoryInterface'

  App\User\Infrastructure\Persistence\DoctrineUserRepository:
    autowire: true
    autoconfigure: true
    public: false
    tags: [ 'doctrine.repository' ]

  App\User\UI\Backoffice\EventSubscriber\:
    resource: '../../EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true
