streaming_channels_list:
  path: /admin/backend/streaming/channels
  controller: App\Streaming\UI\Backoffice\Controller\ListChannelsController
  methods: [GET]

streaming_channels_list_data:
  path: /admin/backend/streaming/channels/data
  controller: App\Streaming\UI\Backoffice\Controller\ListChannelsDataController
  methods: [GET]

streaming_channel_view:
  path: /admin/backend/streaming/channels/{id}
  controller: App\Streaming\UI\Backoffice\Controller\ViewChannelController
  methods: [GET]
  requirements:
    id: '[a-f0-9]{24}'

streaming_channel_create:
  path: /admin/backend/streaming/channels/new
  controller: App\Streaming\UI\Backoffice\Controller\CreateChannelController
  methods: [GET, POST]

streaming_channel_edit:
  path: /admin/backend/streaming/channels/{id}/edit
  controller: App\Streaming\UI\Backoffice\Controller\UpdateChannelController
  methods: [GET, POST]
  requirements:
    id: '[a-f0-9]{24}'

streaming_channel_delete:
  path: /admin/backend/streaming/channels/{id}/delete
  controller: App\Streaming\UI\Backoffice\Controller\DeleteChannelController
  methods: [POST]
  requirements:
    id: '[a-f0-9]{24}'

streaming_channels_bulk_delete:
  path: /admin/backend/streaming/channels/bulk/delete
  controller: App\Streaming\UI\Backoffice\Controller\BulkDeleteChannelController
  methods: [POST]

