<?php

declare(strict_types=1);

namespace Pumukit\StatsBundle\Repository;

use Doctrine\ODM\MongoDB\Repository\DocumentRepository;

/**
 * ViewsAggregationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsAggregationRepository extends DocumentRepository {}
