monolog:
  channels: [ 'deprecation' ]
  handlers:
    deprecation:
      type: stream
      path: '%kernel.logs_dir%/deprecation.log'
      bubble: false
      channels: ['deprecation']

    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
      channels: ['!event', '!deprecation']

    debug_log:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%_debug.log'
      level: info
      max_files: 20
      channels: ['!event', '!deprecation']
