services:
  # Channel Context
  App\Streaming\Channel\Infrastructure\Persistence\DoctrineChannelRepository:
    autowire: true

  App\Streaming\Channel\Domain\Repository\ChannelRepositoryInterface:
    alias: App\Streaming\Channel\Infrastructure\Persistence\DoctrineChannelRepository

  App\Streaming\Channel\Application\:
    resource: '../../Streaming/Channel/Application/*'
    exclude:
      - '../../Streaming/Channel/Application/*/*Query.php'
      - '../../Streaming/Channel/Application/*/*Request.php'
      - '../../Streaming/Channel/Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\Controller\:
    resource: '../../UI/Backoffice/Streaming/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\EventSubscriber\:
    resource: '../../UI/Backoffice/Streaming/EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\Presenter\:
    resource: '../../UI/Backoffice/Streaming/Presenter'
    autowire: true
    autoconfigure: true

