services:
  App\Transcoding\Infrastructure\Persistence\DoctrineJobRepository:
    autowire: true

  App\Transcoding\Domain\Repository\JobRepositoryInterface:
    alias: App\Transcoding\Infrastructure\Persistence\DoctrineJobRepository

  App\Transcoding\Infrastructure\Persistence\DoctrineCpuRepository:
    autowire: true

  App\Transcoding\Domain\Repository\CpuRepositoryInterface:
    alias: App\Transcoding\Infrastructure\Persistence\DoctrineCpuRepository

  App\Transcoding\Application\:
    resource: '../../../../Application/*'
    exclude:
      - '../../../../Application/*/*Query.php'
      - '../../../../Application/*/*Request.php'
      - '../../../../Application/*/*Response.php'
    autowire: true
    autoconfigure: true
    bind:
      $cpus: '%pumukitencode.cpulist%'

  App\Transcoding\UI\Backoffice\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\Transcoding\UI\Backoffice\EventSubscriber\:
    resource: '../../EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true

  App\Transcoding\UI\Backoffice\Presenter\:
    resource: '../../Presenter'
    autowire: true
    autoconfigure: true

