services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # --- CARGA GLOBAL DEL MÓDULO USER ---
  App\IdentityAndAccess\User\:
    resource: '../../'
    exclude:
      - '../../Domain/Model'
      - '../../Infrastructure/Config'
      - '../../**/*{Query,Request,Response,Validator}.php'

  # --- RESTRICCIONES Y ALIAS ESPECÍFICOS ---

  App\IdentityAndAccess\User\Domain\Repository\UserRepositoryInterface:
    alias: App\IdentityAndAccess\User\Infrastructure\Persistence\DoctrineUserRepository

  App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\:
    resource: '../Ui/Backoffice/Http/Controller/'
    tags: ['controller.service_arguments']

  App\IdentityAndAccess\User\Infrastructure\Security\Permission\UserPermissionRegister:
    tags: [ 'pumukit.permission_register' ]
