user_create:
  path: /admin/backend/users
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserController

user_list:
  path: /admin/backend/users
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserController

users_list_data:
  path: /admin/backend/users/data
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserDataController

user_update:
  path: /admin/backend/users/{id}/update
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserController

user_delete:
  path: /admin/backend/users/{id}/update
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserController

user_view:
  path: /admin/backend/users/{id}
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\ListUserController

add_user_to_group:
  path: /admin/backend/group/{id}/add-user
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\AddUserToGroupController
  methods: [POST]

remove_user_to_group:
  path: /admin/backend/group/{id}/remove-user
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\RemoveUserFromGroupController
  methods: [POST]

users_group_data:
  path: /admin/backend/group/{id}/users/data
  controller: App\IdentityAndAccess\User\Infrastructure\Ui\Backoffice\Http\Controller\GroupUsersDataController
