media_processing_jobs_list:
  path: /admin/backend/jobs
  controller: App\UI\Backoffice\MediaProcessing\Controller\ListJobsController
  methods: [GET]

media_processing_jobs_list_data:
  path: /admin/backend/jobs/data
  controller: App\UI\Backoffice\MediaProcessing\Controller\ListJobsDataController
  methods: [GET]

media_processing_job_view:
  path: /admin/backend/jobs/{id}
  controller: App\UI\Backoffice\MediaProcessing\Controller\ViewJobController
  methods: [GET]
  requirements:
    id: '[a-f0-9]{24}'

media_processing_job_cancel:
  path: /admin/backend/jobs/{id}/cancel
  controller: App\UI\Backoffice\MediaProcessing\Controller\CancelJobController
  methods: [POST]
  requirements:
    id: '[a-f0-9]{24}'
