services:
  App\MediaProcessing\Job\Infrastructure\Persistence\DoctrineJobRepository:
    autowire: true

  App\MediaProcessing\Job\Domain\Repository\JobRepositoryInterface:
    alias: App\MediaProcessing\Job\Infrastructure\Persistence\DoctrineJobRepository

  App\MediaProcessing\Job\Application\:
    resource: '../../../MediaProcessing/Job/Application/*'
    exclude:
      - '../../../MediaProcessing/Job/Application/*/*Query.php'
      - '../../../MediaProcessing/Job/Application/*/*Request.php'
      - '../../../MediaProcessing/Job/Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\MediaProcessing\Job\Controller\:
    resource: '../../../UI/Backoffice/MediaProcessing/Job/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\MediaProcessing\Job\Presenter\:
    resource: '../../../UI/Backoffice/MediaProcessing/Job/Presenter'
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\MediaProcessing\Job\EventSubscriber\:
    resource: '../../../UI/Backoffice/MediaProcessing/Job/EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true
