monolog:
  channels: [ 'deprecation' ]
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
      channels: ['!event', '!deprecation']

    debug_log:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%_debug.log'
      level: warning
      max_files: 20
      channels: ['!event', '!deprecation']
