taxonomy_tag_index:
    path: /admin/backend/taxonomy/tags
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\ListTagsController
    methods: [GET]

taxonomy_tag_list_data:
    path: /admin/backend/taxonomy/tags/data
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\ListTagsDataController
    methods: [GET]

taxonomy_tag_children_data:
    path: /admin/backend/taxonomy/tags/{parentId}/children
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\ListTagChildrenDataController
    methods: [GET]

taxonomy_tag_create:
    path: /admin/backend/taxonomy/tags/create
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\CreateTagController
    methods: [GET, POST]

taxonomy_tag_update:
    path: /admin/backend/taxonomy/tags/{id}/update
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\UpdateTagController
    methods: [GET, POST]

taxonomy_tag_delete:
    path: /admin/backend/taxonomy/tags/{id}/delete
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\DeleteTagController
    methods: [POST]

taxonomy_tag_bulk_delete:
    path: /admin/backend/taxonomy/tags/bulk-delete
    controller: App\UI\Backoffice\ContentManagement\Taxonomy\Controller\BulkDeleteTagsController
    methods: [POST]

