<?php

return [
    ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Pumukit\BaseLivePlayerBundle\PumukitBaseLivePlayerBundle::class => ['all' => true],
    Pumukit\BasePlayerBundle\PumukitBasePlayerBundle::class => ['all' => true],
    Pumukit\CoreBundle\PumukitCoreBundle::class => ['all' => true],
    Pumukit\EncoderBundle\PumukitEncoderBundle::class => ['all' => true],
    Pumukit\InspectionBundle\PumukitInspectionBundle::class => ['all' => true],
    Pumukit\PlayerBundle\PumukitPlayerBundle::class => ['all' => true],
    Pumukit\NewAdminBundle\PumukitNewAdminBundle::class => ['all' => true],
    Pumukit\NotificationBundle\PumukitNotificationBundle::class => ['all' => true],
    Pumukit\SchemaBundle\PumukitSchemaBundle::class => ['all' => true],
    Pumukit\StatsBundle\PumukitStatsBundle::class => ['all' => true],
    Pumukit\StatsUIBundle\PumukitStatsUIBundle::class => ['all' => true],
    Pumukit\WebTVBundle\PumukitWebTVBundle::class => ['all' => true],
    Pumukit\WizardBundle\PumukitWizardBundle::class => ['all' => true],
    Pumukit\WorkflowBundle\PumukitWorkflowBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],
];
