dashboard_routes:
  resource: ../src/Dashboard/UI/Backoffice/Resources/config/routes.yaml

multimedia_object_routes:
  resource: ../src/MultimediaObject/UI/Backoffice/Resources/config/routes.yaml

series_routes:
  resource: ../src/Series/UI/Backoffice/Resources/config/routes.yaml

taxonomy_routes:
  resource: ../src/Taxonomy/UI/Backoffice/Resources/config/routes.yaml

user_routes:
  resource: ../src/User/UI/Backoffice/Resources/config/routes.yaml
