analytics_routes:
  resource: ../src/Framework/Analytics/routes.yaml

dashboard_routes:
  resource: ../src/Framework/Dashboard/routes.yaml

multimedia_object_routes:
  resource: ../src/Framework/ContentManagement/MultimediaObject/routes.yaml

playlist_routes:
  resource: ../src/Framework/ContentManagement/Playlist/routes.yaml

series_routes:
  resource: ../src/Framework/ContentManagement/Series/routes.yaml

channel_routes:
  resource: ../src/Framework/Streaming/Channel/routes.yaml

taxonomy_routes:
  resource: ../src/Framework/ContentManagement/Taxonomy/routes.yaml

job_routes:
  resource: ../src/Framework/MediaProcessing/Job/routes.yaml

cpu_routes:
  resource: ../src/Framework/MediaProcessing/Cpu/routes.yaml

user_routes:
  resource: ../src/Framework/IdentityAndAccess/routes.yaml
