analytics_routes:
  resource: ../src/Analytics/UI/Backoffice/Resources/config/routes.yaml

dashboard_routes:
  resource: ../src/Dashboard/UI/Backoffice/Resources/config/routes.yaml

multimedia_object_routes:
  resource: ../src/MultimediaObject/UI/Backoffice/Resources/config/routes.yaml

#notification_routes:
#  resource: ../src/Notification/UI/Backoffice/Resources/config/routes.yaml

playlist_routes:
  resource: ../src/Playlist/UI/Backoffice/Resources/config/routes.yaml

series_routes:
  resource: ../src/Series/UI/Backoffice/Resources/config/routes.yaml

streaming_routes:
  resource: ../src/Streaming/UI/Backoffice/Resources/config/routes.yaml

taxonomy_routes:
  resource: ../src/Taxonomy/UI/Backoffice/Resources/config/routes.yaml

transcoding_routes:
  resource: ../src/Transcoding/UI/Backoffice/Resources/config/routes.yaml

user_routes:
  resource: ../src/User/UI/Backoffice/Resources/config/routes.yaml
