playlist_create:
  path: /admin/backend/playlist/new
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\CreatePlaylistController
  defaults:
    tab: 'general'
  requirements:
    tab: '[a-zA-Z0-9_-]+'

playlist_list:
  path: /admin/backend/playlist
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\ListPlaylistController

playlist_list_data:
  path: /admin/backend/playlist/data
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\ListPlaylistDataController

playlist_bulk_delete:
  path: /admin/backend/playlist/bulk/delete
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\BulkDeletePlaylistController
  methods: [POST]

playlist_delete:
  path: /admin/backend/playlist/{id}/delete
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\DeletePlaylistController

playlist_update:
  path: /admin/backend/playlist/{id}/update
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\UpdatePlaylistController
  methods: [POST]

playlist_view:
  path: /admin/backend/playlist/{id}/{tab}
  controller: App\UI\Backoffice\ContentManagement\Playlist\Controller\ViewPlaylistController
  defaults:
    tab: 'general'
  requirements:
    tab: '[a-zA-Z0-9_-]+'

