role_list:
    path: /admin/backend/roles
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\ListRolesController
    methods: [GET]

role_list_data:
    path: /admin/backend/roles/data
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\ListRolesDataController
    methods: [GET]

role_create:
    path: /admin/backend/roles/create
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\CreateRoleController
    methods: [GET, POST]

role_view:
  path: /admin/backend/roles/{id}/view
  controller: App\UI\Backoffice\ContentManagement\Role\Controller\ViewRoleController
  methods: [GET]

role_update:
    path: /admin/backend/roles/{id}/update
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\UpdateRoleController
    methods: [GET, POST]

role_delete:
    path: /admin/backend/roles/{id}/delete
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\DeleteRoleController
    methods: [POST]

role_bulk_delete:
    path: /admin/backend/roles/bulk-delete
    controller: App\UI\Backoffice\ContentManagement\Role\Controller\BulkDeleteRolesController
    methods: [POST]


