media_processing_index:
  path: /admin/backend/media_processing
  controller: App\UI\Backoffice\MediaProcessing\Controller\IndexController

media_processing_jobs_list:
  path: /admin/backend/media_processing/jobs
  controller: App\UI\Backoffice\MediaProcessing\Controller\ListJobsController
  methods: [GET]

media_processing_jobs_list_data:
  path: /admin/backend/media_processing/jobs/data
  controller: App\UI\Backoffice\MediaProcessing\Controller\ListJobsDataController
  methods: [GET]

media_processing_job_view:
  path: /admin/backend/media_processing/jobs/{id}
  controller: App\UI\Backoffice\MediaProcessing\Controller\ViewJobController
  methods: [GET]
  requirements:
    id: '[a-f0-9]{24}'

media_processing_job_cancel:
  path: /admin/backend/media_processing/jobs/{id}/cancel
  controller: App\UI\Backoffice\MediaProcessing\Controller\CancelJobController
  methods: [POST]
  requirements:
    id: '[a-f0-9]{24}'

media_processing_cpus_list:
  path: /admin/backend/media_processing/cpus
  controller: App\UI\Backoffice\MediaProcessing\Controller\ListCpusController
  methods: [GET]

media_processing_cpu_toggle_maintenance:
  path: /admin/backend/media_processing/cpus/{cpuName}/maintenance/{action}
  controller: App\UI\Backoffice\MediaProcessing\Controller\ToggleCpuMaintenanceController
  methods: [POST]
  requirements:
    action: 'activate|deactivate'

