multimediaobject_view:
  path: /admin/backend/multimedia-object/{id}/{tab}
  controller: App\MultimediaObject\UI\Backend\Controller\ViewMultimediaObjectController
  defaults:
    tab: 'general'
  requirements:
    tab: general|media|metadata|owners|people|publication|tags
