<?php

declare(strict_types=1);

namespace Pumukit\SchemaBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('pumukit_schema');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
            ->scalarNode('default_head_video')
            ->defaultFalse()
            ->info('Default head video on platform')
            ->end()
            ->scalarNode('default_tail_video')
            ->defaultFalse()
            ->info('Default tail video on platform')
            ->end()
            ->booleanNode('send_email_on_user_added_as_owner')
            ->defaultFalse()
            ->info('Activate send email on user added as owner')
            ->end()
            ->booleanNode('user_can_reject_owner_of_multimedia_object')
            ->defaultFalse()
            ->info('On user added as owner email received, the user can reject the association')
            ->end()
            ->scalarNode('multimedia_object_add_owner_subject')
            ->defaultValue('PuMuKIT - Added as owner on multimedia object')
            ->info('Email subject on event add owner to multimedia object')
            ->end()
            ->scalarNode('multimedia_object_add_owner_template')
            ->defaultValue('@PumukitNewAdmin/MultimediaObject/Owner/email.html.twig')
            ->info('Email template on add owner to multimedia object')
            ->end()
            ->scalarNode('default_copyright')
            ->defaultValue('')
            ->info('Default copyright MultimediaObject')
            ->end()
            ->scalarNode('default_license')
            ->defaultValue('')
            ->info('Default license MultimediaObject')
            ->end()
            ->scalarNode('default_series_pic')
            ->defaultValue('/bundles/pumukitschema/images/series_folder.png')
            ->info('Default Series picture')
            ->end()
            ->scalarNode('default_playlist_pic')
            ->defaultValue('/bundles/pumukitschema/images/playlist_folder.png')
            ->info('Default Playlist picture')
            ->end()
            ->scalarNode('default_video_pic')
            ->defaultValue('/bundles/pumukitschema/images/video_none.jpg')
            ->info('Default video picture')
            ->end()
            ->scalarNode('default_audio_hd_pic')
            ->defaultValue('/bundles/pumukitschema/images/audio_hd.svg')
            ->info('Default audio HD picture')
            ->end()
            ->scalarNode('default_audio_sd_pic')
            ->defaultValue('/bundles/pumukitschema/images/audio_sd.svg')
            ->info('Default audio SD picture')
            ->end()
            ->scalarNode('event_default_poster_text_color')
            ->defaultValue('#ffffff')
            ->info('Default poster text color')
            ->end()
            ->booleanNode('enable_add_user_as_person')
            ->defaultTrue()
            ->info('Add logged in User as Person to MultimediaObjects')
            ->end()
            ->scalarNode('personal_scope_role_code')
            ->defaultValue('owner')
            ->info('Role code related to Personal Scope User to use as EmbeddedPerson')
            ->end()
            ->booleanNode('personal_scope_delete_owners')
            ->defaultFalse()
            ->info('Allow Personal Scope users to delete other owners of Series and MultimediaObjects')
            ->end()
            ->booleanNode('gen_user_salt')
            ->defaultTrue()
            ->info('Disable the generation of a random user salt. Required to use PuMuKIT as a CAS user provider.')
            ->end()
            ->arrayNode('external_permissions')
            ->info('External permissions for user profiles.')
            ->prototype('array')
            ->children()
            ->scalarNode('role')
            ->info('Code for the permission. The role Must start with \'ROLE_\'')
            ->isRequired()
            ->end()
            ->scalarNode('description')
            ->isRequired()
            ->end()
            ->arrayNode('dependencies')
            ->info('Dependencies for the given permission. (Other permissions that have to be enabled when this one is.)')
            ->children()
            ->arrayNode('global')
            ->info('Global scope dependencies.')
            ->isRequired()
            ->prototype('scalar')->end()
            ->end()
            ->arrayNode('personal')
            ->info('Personal scope dependencies.')
            ->isRequired()
            ->prototype('scalar')->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
