pumukitnewadmin_playlistpic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::createAction
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlistpic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::updateAction

pumukitnewadmin_playlistpic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::deleteAction


pumukitnewadmin_playlistpic_up:
    path: /{id}/up
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::upAction


pumukitnewadmin_playlistpic_down:
    path: /{id}/down
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::downAction


pumukitnewadmin_playlistpic_list:
    path: /{id}/list
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::listAction

pumukitnewadmin_playlistpic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::uploadAction

pumukitnewadmin_playlistpic_picstoaddlist:
    path: /{id}/picstoaddlist
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::picstoaddlistAction

pumukitnewadmin_playlistpic_banner:
    path: /{id}/banner
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistPicController::bannerAction
