pumukitnewadmin_playlist_index:
    path: /
    methods: [GET]
    defaults:

        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_playlist_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::searchAction

pumukitnewadmin_playlist_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::createAction
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlist_update:
    path: /{id}/update
    methods: [GET, POST, DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::updateAction

pumukitnewadmin_playlist_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_playlist_list

pumukitnewadmin_playlist_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlist_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::listAction

pumukitnewadmin_playlist_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistController::showAction
