<?php

namespace Pumukit\DirectBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectRepository extends DocumentRepository
{
}
