services:
  App\MediaProcessing\Cpu\Infrastructure\Persistence\DoctrineCpuRepository:
    autowire: true

  App\MediaProcessing\Cpu\Domain\Repository\CpuRepositoryInterface:
    alias: App\MediaProcessing\Cpu\Infrastructure\Persistence\DoctrineCpuRepository

  App\MediaProcessing\Cpu\Application\:
    resource: '../../../MediaProcessing/Cpu/Application/*'
    exclude:
      - '../../../MediaProcessing/Cpu/Application/*/*Query.php'
      - '../../../MediaProcessing/Cpu/Application/*/*Request.php'
      - '../../../MediaProcessing/Cpu/Application/*/*Response.php'
    autowire: true
    autoconfigure: true
    bind:
      $cpus: '%pumukitencode.cpulist%'

  App\UI\Backoffice\MediaProcessing\Controller\:
    resource: '../../../UI/Backoffice/MediaProcessing/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\MediaProcessing\EventSubscriber\:
    resource: '../../../UI/Backoffice/MediaProcessing/EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\MediaProcessing\Presenter\:
    resource: '../../../UI/Backoffice/MediaProcessing/Presenter'
    autowire: true
    autoconfigure: true

