<?php

namespace Pumukit\EncoderBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends DocumentRepository
{
    /**
     * Find all jobs with given status
     */
    public function findWithStatus(array $status)
    {
        return $this->createQueryBuilder()
          ->field('status')->in($status)
          ->getQuery()
          ->execute();
    }

    /**
     * Find the job with higher priority with given status
     */
    public function findHigherPriorityWithStatus(array $status)
    {
        return $this->createQueryBuilder()
          ->field('status')->in($status)
          ->sort('priority', 'desc')
          ->sort('timeini', 'asc')
          ->getQuery()
          ->getSingleResult();
    }

    /**
     * Find all jobs with given multimedia object id
     */
    public function findByMultimediaObjectId($mmId)
    {
        return $this->createQueryBuilder()
          ->field('mm_id')->equals($mmId)
          ->getQuery()
          ->execute();
    }
}