<?php

namespace Pumukit\SchemaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends DocumentRepository
{
    public function findByCodAndEmail($roleCode, $email)
    {
        $person = $this->getDocumentManager()
            ->getRepository('PumukitSchemaBundle:MultimediaObject')
            ->findOnePersonWithRoleCodeAndEmail($roleCode, $email);
        // TODO
        /* $byEmail = $this->createQueryBuilder() */
        /*   ->field('email')->equals($email); */
        return $person;
    }
}
