<?php

namespace Pumukit\SchemaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * RoleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends DocumentRepository
{
    /**
     * Find all roles in the repository order by rank.
     *
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder()
            ->sort('rank', -1)
            ->getQuery()
            ->execute()
        ;
    }
}
