<?php

namespace Pumukit\SchemaBundle\Repository;

use Gedmo\Tree\Document\MongoDB\Repository\MaterializedPathRepository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends MaterializedPathRepository
{
}
