<?php

namespace Pumukit\SchemaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserClearanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClearanceRepository extends DocumentRepository
{
    /**
     * Change default
     *
     * @param boolean $default
     */
    public function changeDefault($default=true)
    {
        $this->createQueryBuilder()
            ->update()
            ->multiple(true)
            ->field('default')->set(!$default)
            ->field('default')->equals($default)
            ->getQuery()
            ->execute();
    }
}