<?php

namespace Pumukit\SchemaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Pumukit\SchemaBundle\Security\Clearance;

/**
 * UserClearanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClearanceRepository extends DocumentRepository
{
    /**
     * Change default
     *
     * @param boolean $default
     */
    public function changeDefault($default=true)
    {
        $this->createQueryBuilder()
            ->update()
            ->multiple(true)
            ->field('default')->set(!$default)
            ->field('default')->equals($default)
            ->getQuery()
            ->execute();
    }

    /**
     * Find candidate for being default
     *
     * Candidate:
     * - Less amount of clearances
     */
    public function findDefaultCandidate()
    {
        $count = 0;
        $size = -1;
        $totalClearances = count(Clearance::$clearanceDescription);
        do {
            if ($count > 0) break;
            ++$size;
            $count = $this->createQueryBuilder()
                ->field('clearances')->size($size)
                ->count()
                ->getQuery()
                ->execute();
        } while ($size <= $totalClearances);

        if ($count > 0) {
            return $this->createQueryBuilder()
                ->field('clearances')->size($size)
                ->getQuery()
                ->getSingleResult();
        }

        return null;
   }
}