services:
  # Channel Context
  App\Streaming\Channel\Infrastructure\Persistence\DoctrineChannelRepository:
    autowire: true

  App\Streaming\Channel\Domain\Repository\ChannelRepositoryInterface:
    alias: App\Streaming\Channel\Infrastructure\Persistence\DoctrineChannelRepository

  App\Streaming\Channel\Application\:
    resource: '../../../Streaming/Channel/Application/*'
    exclude:
      - '../../../Streaming/Channel/Application/*/*Query.php'
      - '../../../Streaming/Channel/Application/*/*Request.php'
      - '../../../Streaming/Channel/Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\Channel\Controller\:
    resource: '../../../UI/Backoffice/Streaming/Channel/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\Channel\EventSubscriber\:
    resource: '../../../UI/Backoffice/Streaming/Channel/EventSubscriber'
    tags: [ 'kernel.event_subscriber' ]
    autowire: true
    autoconfigure: true

  App\UI\Backoffice\Streaming\Channel\Presenter\:
    resource: '../../../UI/Backoffice/Streaming/Channel/Presenter'
    autowire: true
    autoconfigure: true

