series_create:
  path: /admin/backend/series/new
  controller: App\Series\UI\Backend\Controller\CreateSeriesController

series_list:
  path: /admin/backend/series
  controller: App\Series\UI\Backend\Controller\ListSeriesController

series_list_data:
  path: /admin/backend/series/data
  controller: App\Series\UI\Backend\Controller\ListSeriesDataController

series_view:
  path: /admin/backend/series/{id}/{tab}
  controller: App\Series\UI\Backend\Controller\ViewSeriesController
  defaults:
    tab: 'objects'
  requirements:
    tab: objects|edit|template

series_multimedia_data:
  path: /admin/backend/series/{id}/multimedia/data
  controller: App\Series\UI\Backend\Controller\ViewSeriesMultimediaObjectsDataController
