[program:messenger-events]
command=php /srv/pumukit/bin/console messenger:consume pumukit.youtube.events --time-limit=3600 --memory-limit=128M
user=www-data
numprocs=2
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/srv/pumukit/var/log/messenger_events.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/srv/pumukit/var/log/messenger_events_error.log
stderr_logfile_maxbytes=10MB

[program:messenger-notifications]
command=php /srv/pumukit/bin/console messenger:consume pumukit.youtube.notifications --time-limit=3600 --memory-limit=128M
user=www-data
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/srv/pumukit/var/log/messenger_notifications.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/srv/pumukit/var/log/messenger_notifications_error.log
stderr_logfile_maxbytes=10MB

[program:messenger-quota-waiting]
command=php /srv/pumukit/bin/console messenger:consume pumukit.youtube.quota.waiting --time-limit=3600 --memory-limit=128M
user=www-data
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/srv/pumukit/var/log/messenger_quota_waiting.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/srv/pumukit/var/log/messenger_quota_waiting_error.log
stderr_logfile_maxbytes=10MB
