pumukitwizard_js:
    path: /admin/wizard/pumukit_wizard.js
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: '@PumukitWizard/pumukit_wizard.js.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: js

pumukitwizard_default:
    resource: "@PumukitWizardBundle/Resources/config/routes/default.yml"
    prefix: /admin/wizard

pumukitwizard_simple:
    resource: "@PumukitWizardBundle/Resources/config/routes/simple.yml"
    prefix: /admin/simplewizard
