pumukitwizard_js:
    path: /admin/wizard/pumukit_wizard.js
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: '@PumukitWizard/pumukit_wizard.js.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: js

pumukit_wizard:
  resource: "@PumukitWizardBundle/Controller/"
  type:     annotation
  prefix:   /
