<?php

namespace Pumukit\SchemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonInMultimediaObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonInMultimediaObjectRepository extends EntityRepository
{
}