<?php

namespace Pumukit\SchemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesTypeRepository extends EntityRepository
{
}
