<?php

namespace Pumukit\SchemaBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
// Review /vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends NestedTreeRepository
{
}