services:
  # <service id="pumukitcore.twig_loader.customwebtv_bundle" class="Pumukit\CoreBundle\Services\TwigTemplateLoaderService">
  #   <argument type="service" id="templating.locator" />
  #   <argument type="service" id="templating.name_parser" />
  #   <argument>%kernel.project_dir%</argument>
  #   <argument>WebTVBundle</argument>
  #   <argument>{customName}WebTVBundle</argument>
  #   <tag name="twig.loader" priority="1"/>
  # </service>
#    pumukit_prueba_web_tv.example:
#        class: Pumukit\Prueba\WebTVBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
