services:
  App\MultimediaObject\Application\:
    resource: '../../Application/*'
    exclude:
      - '../../Application/*/*Query.php'
      - '../../Application/*/*Request.php'
      - '../../Application/*/*Response.php'
    autowire: true
    autoconfigure: true

  App\MultimediaObject\UI\Backend\Controller\:
    resource: '../../UI/Backend/Controller'
    tags: [ 'controller.service_arguments' ]
    autowire: true
    autoconfigure: true

  App\MultimediaObject\Domain\MultimediaObjectRepositoryInterface: '@App\MultimediaObject\Infrastructure\Persistence\DoctrineMultimediaObjectRepository'

  App\MultimediaObject\Infrastructure\Persistence\DoctrineMultimediaObjectRepository:
    autowire: true
    autoconfigure: true
    public: false
    tags: [ 'doctrine.repository' ]
